server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: environmental-monitoring
    
  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise
    username: postgres
    password: ala1nna
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
        
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
        
logging:
  level:
    com.fairchild.envmonitor: DEBUG
    org.springframework.web: INFO
    org.springframework.cache: DEBUG
    
# External API configurations
external-apis:
  weather-gov:
    base-url: https://api.weather.gov
    user-agent: Environmental Monitoring Dashboard by Ty Fairchild
    
  open-meteo:
    base-url: https://api.open-meteo.com/v1
    
  marine-data:
    base-url: https://api.tidesandcurrents.noaa.gov/api/prod/datagetter
    
  air-quality:
    base-url: https://api.airnowapi.org/aq
    api-key: your_airnow_api_key_here
    
# Scheduler configurations
scheduler:
  weather-fetch-interval: 300000  # 5 minutes in milliseconds
  marine-fetch-interval: 600000   # 10 minutes
  air-quality-interval: 900000    # 15 minutes
  fire-data-interval: 3600000     # 1 hour
